'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SFDL.NET3.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktive Aufgaben ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppTasks_ListView_ActiveTasks_Header() As String
            Get
                Return ResourceManager.GetString("AppTasks_ListView_ActiveTasks_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aufgaben Historie ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppTasks_ListView_TaskHistory_Header() As String
            Get
                Return ResourceManager.GetString("AppTasks_ListView_TaskHistory_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Container &apos;{0}&apos; geschlossen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CloseSFDLContainer_AppTask_Completed_Message() As String
            Get
                Return ResourceManager.GetString("CloseSFDLContainer_AppTask_Completed_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kann die Sitzung nicht schließen da diese aktiv ist (Download oder Entpackvorgang) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CloseSFDLContainer_AppTask_Faulted_Message() As String
            Get
                Return ResourceManager.GetString("CloseSFDLContainer_AppTask_Faulted_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Container wird entfernt/geschlossen.... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CloseSFDLContainer_AppTask_Start_Message() As String
            Get
                Return ResourceManager.GetString("CloseSFDLContainer_AppTask_Start_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL wählen: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_ChooseSFDL() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_ChooseSFDL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verschlüsselt: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_Encrypted() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_Encrypted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Datei Informationen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_GroupBoxHeader() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_GroupBoxHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximal erlaubte Threads Anzahl: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_MaxThreads() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_MaxThreads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl der Pakete: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_PackagesCount() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_PackagesCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Server Standort: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_ServerLocation() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_ServerLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gesamtgröße: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_TotalSize() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_TotalSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uploader: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ContainerInfo_Uploader() As String
            Get
                Return ResourceManager.GetString("ContainerInfo_Uploader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Container schließen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadItems_ContextMenu_CloseSFDLContainer() As String
            Get
                Return ResourceManager.GetString("DownloadItems_ContextMenu_CloseSFDLContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Dateien im diesem Paket markieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadItems_ContextMenu_MarkAllItemsInPackage() As String
            Get
                Return ResourceManager.GetString("DownloadItems_ContextMenu_MarkAllItemsInPackage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beinhaltenden Ordner öffnen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadItems_ContextMenu_OpenParentFolder() As String
            Get
                Return ResourceManager.GetString("DownloadItems_ContextMenu_OpenParentFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Dateien im diesem Paket demarkieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadItems_ContextMenu_UnMarkAllItemsInPackage() As String
            Get
                Return ResourceManager.GetString("DownloadItems_ContextMenu_UnMarkAllItemsInPackage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei bereits Vollständig ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_AlreadyDownloaded() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_AlreadyDownloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download abgeschlossen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Completed() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download abgeschlossen (Checksumme: Fehler) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Completed_HashInvalid() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Completed_HashInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download abgeschlossen (Checksumme: OK) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Completed_HashValid() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Completed_HashValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Unbekannt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Authentifizierung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_AuthError() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_AuthError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Verbindung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_ConnectionError() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_ConnectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Verzeichnis nicht gefunden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_DirectoryNotFound() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_DirectoryNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Dateiname zu lang ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_FileNameTooLong() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_FileNameTooLong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Datei nicht gefunden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_FileNotFound() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Serverfehler ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_InternalServerError() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_InternalServerError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Zu wenig Speicherplatz ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_NotEnoughDiskSpace() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_NotEnoughDiskSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Server nicht erreichbar ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_ServerDown() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_ServerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler: Server Voll ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Failed_ServerFull() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Failed_ServerFull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die In Warteschlange ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Queued() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Queued", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Retry {0}/{1} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Retry() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Retry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warte {0} Sek. auf Retry {1}/{2} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_RetryWait() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_RetryWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download läuft ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Running() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download wartet auf Start.... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_RunningWait() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_RunningWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download gestoppt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DownloadStatus_Stopped() As String
            Get
                Return ResourceManager.GetString("DownloadStatus_Stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download wird gestartet... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ETA_AppTask_Start() As String
            Get
                Return ResourceManager.GetString("ETA_AppTask_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download läuft - Speed: {0} MB/s | ETA: {1} | {2} % ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ETA_AppTask_Status_1_Message() As String
            Get
                Return ResourceManager.GetString("ETA_AppTask_Status_1_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download läuft - {0} % ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ETA_AppTask_Status_2_Message() As String
            Get
                Return ResourceManager.GetString("ETA_AppTask_Status_2_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download läuft... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ETA_AppTask_Status_3_Message() As String
            Get
                Return ResourceManager.GetString("ETA_AppTask_Status_3_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es läuft aktuell noch ein Download oder Entpackvorgang. Wollen Sie die Anwendung trotzdem beenden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ExitApplication_Prompt_Message() As String
            Get
                Return ResourceManager.GetString("ExitApplication_Prompt_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL.NET beenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ExitApplication_Prompt_Title() As String
            Get
                Return ResourceManager.GetString("ExitApplication_Prompt_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aufgaben ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Expander_Header_Tasks() As String
            Get
                Return ResourceManager.GetString("Expander_Header_Tasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL.NET 3 wird zum ersten Mal gestartet oder der Installationspfad hat sich geändert.
        '''
        '''Deshalb muss SFDL.NET 3 einmalig &quot;als Administrator&quot; gestartet werden damit die Dateiendung *.sfdl registriert wird.
        '''
        '''Wollen Sie die Anwendung jetzt mit Administratorrechte neustarten? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property InstallPathChangedPrompt() As String
            Get
                Return ResourceManager.GetString("InstallPathChangedPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verfügbare Instant Video Streams: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property InstantVideo_AvailableStreams() As String
            Get
                Return ResourceManager.GetString("InstantVideo_AvailableStreams", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der VLC PLayer ist auf dem System nicht installiert. Bitte installieren Sie den VLC Player um Instant Video zu nutzen! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property InstantVideo_Message_VLCNotInstalled_Message() As String
            Get
                Return ResourceManager.GetString("InstantVideo_Message_VLCNotInstalled_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateiname ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ListView_DownloadItems_Header_Filename() As String
            Get
                Return ResourceManager.GetString("ListView_DownloadItems_Header_Filename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateigröße ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ListView_DownloadItems_Header_Filesize() As String
            Get
                Return ResourceManager.GetString("ListView_DownloadItems_Header_Filesize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fortschritt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ListView_DownloadItems_Header_Progress() As String
            Get
                Return ResourceManager.GetString("ListView_DownloadItems_Header_Progress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ListView_DownloadItems_Header_Speed() As String
            Get
                Return ResourceManager.GetString("ListView_DownloadItems_Header_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ListView_DownloadItems_Header_Status() As String
            Get
                Return ResourceManager.GetString("ListView_DownloadItems_Header_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Extra() As String
            Get
                Return ResourceManager.GetString("MainMenu_Extra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nach dem Download ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Extra_AfterDownload() As String
            Get
                Return ResourceManager.GetString("MainMenu_Extra_AfterDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Loader schließen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Extra_AfterDownload_ExitLoader() As String
            Get
                Return ResourceManager.GetString("MainMenu_Extra_AfterDownload_ExitLoader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PC herunterfahren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Extra_AfterDownload_ShutdownComputer() As String
            Get
                Return ResourceManager.GetString("MainMenu_Extra_AfterDownload_ShutdownComputer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_File() As String
            Get
                Return ResourceManager.GetString("MainMenu_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_File_Exit() As String
            Get
                Return ResourceManager.GetString("MainMenu_File_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_File_OpenFile() As String
            Get
                Return ResourceManager.GetString("MainMenu_File_OpenFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_File_Settings() As String
            Get
                Return ResourceManager.GetString("MainMenu_File_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Help() As String
            Get
                Return ResourceManager.GetString("MainMenu_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Help_About() As String
            Get
                Return ResourceManager.GetString("MainMenu_Help_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Pakete einklappen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modifiy_CollapeseAllPackages() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modifiy_CollapeseAllPackages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Pakete ausklappen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modifiy_ExpandAllPackages() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modifiy_ExpandAllPackages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Dateien markieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modifiy_MarkAllFiles() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modifiy_MarkAllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Dateien demarkieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modifiy_UnmarkAllFiles() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modifiy_UnmarkAllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modify() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Downloads entfernen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modify_CloseAlleDownloads() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modify_CloseAlleDownloads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle abgeschlossenen Downloads entfernen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainMenu_Modify_RemoveAllCompletedDownloads() As String
            Get
                Return ResourceManager.GetString("MainMenu_Modify_RemoveAllCompletedDownloads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Instant Video ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainToolbar_InstandVideo() As String
            Get
                Return ResourceManager.GetString("MainToolbar_InstandVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download starten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainToolBar_StartDownload() As String
            Get
                Return ResourceManager.GetString("MainToolBar_StartDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download stoppen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MainToolBar_StopDownload() As String
            Get
                Return ResourceManager.GetString("MainToolBar_StopDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Datei(en) öffnen: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenFileDialog_Title() As String
            Get
                Return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL &apos;{0}&apos; geöffnet und anschließend gelöscht ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_AppTask_Completed_1_Message() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_AppTask_Completed_1_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL &apos;{0}&apos; geöffnet ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_AppTask_Completed_2_Message() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_AppTask_Completed_2_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL &apos;{0}&apos; teilweise geöffnet - Einer oder mehrere Container konnten nicht gelesen werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_AppTask_Faulted_Message() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_AppTask_Faulted_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Container &apos;{0}&apos; wird geöffnet... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_AppTask_Start_Message() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_AppTask_Start_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; - SFDL entschlüsseln abgebrochen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_Decrypt_Aborted_Message() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_Decrypt_Aborted_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; - Versuch denn FTP Link, Server ist wahrscheinlich offline ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_Exception_FTPDown() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_Exception_FTPDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Container &apos;{0}&apos; ist bereits geöffnet! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_Exception_SFDLContainerAlreadyOpen() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_Exception_SFDLContainerAlreadyOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; - Dieser SFDL Container ist inkompatibel mit dieser Programmversion! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_Exception_SFDLFileNotCompatible() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_Exception_SFDLFileNotCompatible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein Passwort ein um den SFDL Container {0} zu entschlüsseln: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_Prompt_Decrypt_Message() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_Prompt_Decrypt_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL entschlüsseln ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenSFDL_Prompt_Decrypt_Title() As String
            Get
                Return ResourceManager.GetString("OpenSFDL_Prompt_Decrypt_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} Download gestoppt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PostDownload_AppTask_Completed_1_Message() As String
            Get
                Return ResourceManager.GetString("PostDownload_AppTask_Completed_1_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} Download beendet ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PostDownload_AppTask_Completed_2_Message() As String
            Get
                Return ResourceManager.GetString("PostDownload_AppTask_Completed_2_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download Verzeichnis existiert nicht! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PreDownloadCheck_Exception_DownloadDirectoryNotExists() As String
            Get
                Return ResourceManager.GetString("PreDownloadCheck_Exception_DownloadDirectoryNotExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Du hat keinen Download Pfad in den Einstellungen hinterlegt! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PreDownloadCheck_Exception_NoDownloadDirectory() As String
            Get
                Return ResourceManager.GetString("PreDownloadCheck_Exception_NoDownloadDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Du musst mind. einen Eintrag zum Download auswählen! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PreDownloadCheck_Exception_NothingSelected() As String
            Get
                Return ResourceManager.GetString("PreDownloadCheck_Exception_NothingSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abgeschlossene Container entfernt/geschlossen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveAllCompletedDownloads_AppTask_Completed_Message() As String
            Get
                Return ResourceManager.GetString("RemoveAllCompletedDownloads_AppTask_Completed_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine abgeschlossene Container vorhanden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveAllCompletedDownloads_AppTask_Faulted_Message() As String
            Get
                Return ResourceManager.GetString("RemoveAllCompletedDownloads_AppTask_Faulted_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entferne/Schließe abgeschlossene Container... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveAllCompletedDownloads_AppTask_Start_Message() As String
            Get
                Return ResourceManager.GetString("RemoveAllCompletedDownloads_AppTask_Start_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Container entfernt/geschlossen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveAllDownloads_AppTask_Complete_Message() As String
            Get
                Return ResourceManager.GetString("RemoveAllDownloads_AppTask_Complete_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diese Funktion kann nicht genutzt werden solange der Download aktiv ist. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveAllDownloads_AppTask_Faulted_Message() As String
            Get
                Return ResourceManager.GetString("RemoveAllDownloads_AppTask_Faulted_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entferne/Schließe alle Container... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveAllDownloads_AppTask_Start_Message() As String
            Get
                Return ResourceManager.GetString("RemoveAllDownloads_AppTask_Start_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erweiterte Download Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_AdvancedDownloadSettings() As String
            Get
                Return ResourceManager.GetString("Settings_AdvancedDownloadSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erweiterte Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_AdvancedSettings() As String
            Get
                Return ResourceManager.GetString("Settings_AdvancedSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die API Schlüssel ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_APIKeys() As String
            Get
                Return ResourceManager.GetString("Settings_APIKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archive nach dem Download Automatisch entpacken ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_AutomaticUnRAR() As String
            Get
                Return ResourceManager.GetString("Settings_AutomaticUnRAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Click&apos;n&apos;Load aktivieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_ClicknLoad() As String
            Get
                Return ResourceManager.GetString("Settings_ClicknLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unterordner pro Download erstellen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_CreateSubfolderEachDownload() As String
            Get
                Return ResourceManager.GetString("Settings_CreateSubfolderEachDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unterordner pro Paket erstellen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_CreateSubfolderEachPackage() As String
            Get
                Return ResourceManager.GetString("Settings_CreateSubfolderEachPackage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport deaktivieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_DisableSpeedreport() As String
            Get
                Return ResourceManager.GetString("Settings_DisableSpeedreport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download Verzeichnis ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_DownloadDir() As String
            Get
                Return ResourceManager.GetString("Settings_DownloadDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Du musst einen Ordner wählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_DownloadDirectory_ChooseFolder() As String
            Get
                Return ResourceManager.GetString("Settings_DownloadDirectory_ChooseFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das gewählte Verzeichnis existiert nicht! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_DownloadDirectory_DirectoryNotFalid() As String
            Get
                Return ResourceManager.GetString("Settings_DownloadDirectory_DirectoryNotFalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_DownloadSettings() As String
            Get
                Return ResourceManager.GetString("Settings_DownloadSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Folgende Dateien ignorieren: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_ExcludeFiles() As String
            Get
                Return ResourceManager.GetString("Settings_ExcludeFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Existierende Datei: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_ExistingFile() As String
            Get
                Return ResourceManager.GetString("Settings_ExistingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fortsetzten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_ExistingFile_Append() As String
            Get
                Return ResourceManager.GetString("Settings_ExistingFile_Append", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überschreiben ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_ExistingFile_Overwrite() As String
            Get
                Return ResourceManager.GetString("Settings_ExistingFile_Overwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Allgemeine Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_GeneralSettings() As String
            Get
                Return ResourceManager.GetString("Settings_GeneralSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein gültiges RegEx. Pattern an, welches zur Blacklist hinzugefügt wird. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Input_AddBlacklistItem_Message() As String
            Get
                Return ResourceManager.GetString("Settings_Input_AddBlacklistItem_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das eingebene RegEx. Pattern ist nicht gültig! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Input_AddBlacklistItem_RegexNotValid_Message() As String
            Get
                Return ResourceManager.GetString("Settings_Input_AddBlacklistItem_RegexNotValid_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die RegEx. Pattern zur Blacklist hinzufügen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Input_AddBlacklistItem_Title() As String
            Get
                Return ResourceManager.GetString("Settings_Input_AddBlacklistItem_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie das Kennwort ein, welches zur Liste hinzugefügt wird. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Input_AddUnRARPassword_Message() As String
            Get
                Return ResourceManager.GetString("Settings_Input_AddUnRARPassword_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Passwort hinzufügen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Input_AddUnRARPassword_Title() As String
            Get
                Return ResourceManager.GetString("Settings_Input_AddUnRARPassword_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Instant Video ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_InstantVideo() As String
            Get
                Return ResourceManager.GetString("Settings_InstantVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die IP Adresse: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_IPAdress() As String
            Get
                Return ResourceManager.GetString("Settings_IPAdress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Language_English() As String
            Get
                Return ResourceManager.GetString("Settings_Language_English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Language_German() As String
            Get
                Return ResourceManager.GetString("Settings_Language_German", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximale Retries: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_MaximumRetries() As String
            Get
                Return ResourceManager.GetString("Settings_MaximumRetries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximale Threads: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_MaximumThreads() As String
            Get
                Return ResourceManager.GetString("Settings_MaximumThreads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ins Tray minimieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_MinimizeToTray() As String
            Get
                Return ResourceManager.GetString("Settings_MinimizeToTray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateien im Container nicht automatisch auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_NotMarkAllFilesInContainer() As String
            Get
                Return ResourceManager.GetString("Settings_NotMarkAllFilesInContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kennwortliste: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_PasswordList() As String
            Get
                Return ResourceManager.GetString("Settings_PasswordList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Port: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Port() As String
            Get
                Return ResourceManager.GetString("Settings_Port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standby verhindern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_PreventStandy() As String
            Get
                Return ResourceManager.GetString("Settings_PreventStandy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das ausgewählte RegEx. Pattern aus der Blacklist entfernen? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Question_RemoveBlacklistItem_Message() As String
            Get
                Return ResourceManager.GetString("Settings_Question_RemoveBlacklistItem_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die RegEx. Pattern aus Blacklist entfernen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Question_RemoveBlacklistItem_Title() As String
            Get
                Return ResourceManager.GetString("Settings_Question_RemoveBlacklistItem_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das ausgewählte Passwort entfernen? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Question_RemoveUnRARPassword_Message() As String
            Get
                Return ResourceManager.GetString("Settings_Question_RemoveUnRARPassword_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Passwort entfernen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Question_RemoveUnRARPassword_Title() As String
            Get
                Return ResourceManager.GetString("Settings_Question_RemoveUnRARPassword_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Remote Control ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_RemoteControl() As String
            Get
                Return ResourceManager.GetString("Settings_RemoteControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Remote Control aktivieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_RemoteControl_Enable() As String
            Get
                Return ResourceManager.GetString("Settings_RemoteControl_Enable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archive nach erfolgreichem Entpacken löschen lassen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_RemoveRARFiles() As String
            Get
                Return ResourceManager.GetString("Settings_RemoveRARFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Datei nach dem Öffnen löschen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_RemoveSFDL() As String
            Get
                Return ResourceManager.GetString("Settings_RemoveSFDL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beim Speichern der Einstellungen ist ein Fehler aufgetreten! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_SaveError() As String
            Get
                Return ResourceManager.GetString("Settings_SaveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einige Einstellung wurden nicht übernommen, da aktuell ein Download aktiv ist.
        '''Starten Sie den Download neu damit alle Einstellungen übernommen werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_SaveSettings_DownloadActive_Message() As String
            Get
                Return ResourceManager.GetString("Settings_SaveSettings_DownloadActive_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich gespeichert! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_SaveSuccessful() As String
            Get
                Return ResourceManager.GetString("Settings_SaveSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen speichern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_SaveTitle() As String
            Get
                Return ResourceManager.GetString("Settings_SaveTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nach Updates suchen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_SearchUpdates() As String
            Get
                Return ResourceManager.GetString("Settings_SearchUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport nach dem Download anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_ShowSpeedreportAfterDownload() As String
            Get
                Return ResourceManager.GetString("Settings_ShowSpeedreportAfterDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_SpeedreportSettings() As String
            Get
                Return ResourceManager.GetString("Settings_SpeedreportSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aussehen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Style() As String
            Get
                Return ResourceManager.GetString("Settings_Style", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Beschreibung verwenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Subfolder_UseDescription() As String
            Get
                Return ResourceManager.GetString("Settings_Subfolder_UseDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Dateiname verwenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Subfolder_UseFilename() As String
            Get
                Return ResourceManager.GetString("Settings_Subfolder_UseFilename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_Title() As String
            Get
                Return ResourceManager.GetString("Settings_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archiv Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_UnrarSettings() As String
            Get
                Return ResourceManager.GetString("Settings_UnrarSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kennwortliste zum Entpacken verwenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_UseUnRARPasswordList() As String
            Get
                Return ResourceManager.GetString("Settings_UseUnRARPasswordList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wartezeit zwischen Retries: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_WaitTimeRetries() As String
            Get
                Return ResourceManager.GetString("Settings_WaitTimeRetries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport in Datei schreiben ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Settings_WriteSpeedreportToFile() As String
            Get
                Return ResourceManager.GetString("Settings_WriteSpeedreportToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport erstellt | {0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Speedreport_AppTask_Completed_Message() As String
            Get
                Return ResourceManager.GetString("Speedreport_AppTask_Completed_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport wird erstellt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Speedreport_AppTask_Start_Message() As String
            Get
                Return ResourceManager.GetString("Speedreport_AppTask_Start_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speedreport Erstellung fehlgeschlagen! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Speedreport_Exception_SpeedreportFailed() As String
            Get
                Return ResourceManager.GetString("Speedreport_Exception_SpeedreportFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archiv {0} | Entpacken: Erfolgreich | Archive löschen: Erfolgreich ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Completed_1_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Completed_1_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archiv {0} | Entpacken: Erfolgreich ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Completed_2_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Completed_2_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archiv {0} | Entpacken: Erfolgreich | Archive löschen: Fehlgeschlagen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Faulted_1_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Faulted_1_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entpacken: Fehlgeschlagen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Faulted_2_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Faulted_2_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archiv {0} wird entpackt.... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Start_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Start_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} - {1}% Entpackt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Status_1_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Status_1_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lösche Archive.... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Status_2_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Status_2_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cracke Passwort Archiv: {0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_AppTask_Status_3_Message() As String
            Get
                Return ResourceManager.GetString("UnRAR_AppTask_Status_3_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cracken des Passworts fehlgeschlagen! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_Exception_CrackPasswordFailed() As String
            Get
                Return ResourceManager.GetString("UnRAR_Exception_CrackPasswordFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zum Entpacken ist ein Passwort nötig, allerdings sind keine Passworter in der Liste oder das Verwenden dieser ist nicht erlaubt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_Exception_NoPasswordsInList() As String
            Get
                Return ResourceManager.GetString("UnRAR_Exception_NoPasswordsInList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein passendes Passwort gefunden! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UnRAR_Exception_NoValidPasswordFound() As String
            Get
                Return ResourceManager.GetString("UnRAR_Exception_NoValidPasswordFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_AffirmativeButton() As String
            Get
                Return ResourceManager.GetString("VariousStrings_AffirmativeButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kommentar ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Comment() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Comment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verbindung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Connection() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Connection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kopieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Copy() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Description() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deaktiviert ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Disabled() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Download Geschwindigkeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_DownloadSpeed() As String
            Get
                Return ResourceManager.GetString("VariousStrings_DownloadSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktiviert ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Enabled() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Error() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateiname ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Filename() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Filename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gesamtdownloadgröße ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_FullDownloadSize() As String
            Get
                Return ResourceManager.GetString("VariousStrings_FullDownloadSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Benötigte Downloadzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_NeededDownloadTime() As String
            Get
                Return ResourceManager.GetString("VariousStrings_NeededDownloadTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_NegativeButton() As String
            Get
                Return ResourceManager.GetString("VariousStrings_NegativeButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neues Update verfügbar! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_NewUpdateAvailable() As String
            Get
                Return ResourceManager.GetString("VariousStrings_NewUpdateAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abspielen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Play() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Save() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Durchsuchen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_SearchFolderFile() As String
            Get
                Return ResourceManager.GetString("VariousStrings_SearchFolderFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SFDL Informationen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_SFDLInformation() As String
            Get
                Return ResourceManager.GetString("VariousStrings_SFDLInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Entpack-Programme, welche zum automatischen Entpacken benötigt werden, sind nicht vorhanden! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_UnRARExecutableMissingException() As String
            Get
                Return ResourceManager.GetString("VariousStrings_UnRARExecutableMissingException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uploader ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Uploader() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Uploader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Username() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Variablen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Variables() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Variables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VariousStrings_Warning() As String
            Get
                Return ResourceManager.GetString("VariousStrings_Warning", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
